<a href="https://colab.research.google.com/github/Maria-ui-sudo/Maria-ui-sudo/blob/main/Clean_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
data={
    "Employee ID":["Anna","John", "Mike", "Sara"],
    "Age":[28,35, 40, 24],
    "Salary":[ 48000,55000,62000, 45000]
}
df=pd.DataFrame(data)
print("Average salary:",df["Salary"].mean)
print("Highest salary:",df["Salary"].max)
print("Employees under 30:")
print(df[df["Age"]<30])

Average salary: <bound method Series.mean of 0    48000
1    55000
2    62000
3    45000
Name: Salary, dtype: int64>
Highest salary: <bound method Series.max of 0    48000
1    55000
2    62000
3    45000
Name: Salary, dtype: int64>
Employees under 30:
  Employee ID  Age  Salary
0        Anna   28   48000
3        Sara   24   45000

#Collecting Data Form a CSV file

In [4]:
import pandas as pd
df=pd.read_csv("sample_data/california_housing_train.csv")
print(df.head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0
1    -114.47     34.40                19.0       7650.0          1901.0
2    -114.56     33.69                17.0        720.0           174.0
3    -114.57     33.64                14.0       1501.0           337.0
4    -114.57     33.57                20.0       1454.0           326.0

   population  households  median_income  median_house_value
0      1015.0       472.0         1.4936             66900.0
1      1129.0       463.0         1.8200             80100.0
2       333.0       117.0         1.6509             85700.0
3       515.0       226.0         3.1917             73400.0
4       624.0       262.0         1.9250             65500.0

In [5]:
display(df.head(10))

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
5,-114.58,33.63,29.0,1387.0,236.0,671.0,239.0,3.3438,74000.0
6,-114.58,33.61,25.0,2907.0,680.0,1841.0,633.0,2.6768,82400.0
7,-114.59,34.83,41.0,812.0,168.0,375.0,158.0,1.7083,48500.0
8,-114.59,33.61,34.0,4789.0,1175.0,3134.0,1056.0,2.1782,58400.0
9,-114.60,34.83,46.0,1497.0,309.0,787.0,271.0,2.1908,48100.0

# Cleaning Data
##Cleaning date means fixing, correcting,and preparing raw data
### Raw dataos  usually messy:


1. Missing values
2.  Wrong values
3. Duplicates
4. Inconsistent formats

##Solutions:


*   Romove missing rows
*   Fill missing values

In [8]:
df.dropna()
df.fillna(0)
df["housing_median_age"].fillna(df["housing_median_age"].mean())

0        15.0
1        19.0
2        17.0
3        14.0
4        20.0
         ...
16995    52.0
16996    36.0
16997    17.0
16998    19.0
16999    52.0
Name: housing_median_age, Length: 17000, dtype: float64

# Removing Duplicates

In [11]:
df["housing_median_age"] = df["housing_median_age"].astype(int)

### Fixing Inconsistent Text
#### Text data may not be consistent.
"NY", "New York", "new york"

In [16]:
df["City"]=df["City"].str.lower()
df["City"]=df["City"].str.strip()

KeyError: 'City'

In [15]:
print(df.columns)

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

##Handling Outliers

Outliers = extreme values.
Age=150
Salary=1000000

Basic Check:

In [19]:
df["housing_median_age"].max()
df["housing_median_age"].min()

1

Remove unrealistic values:

In [23]:
df = df[df["housing_median_age"] <= 100]

In [22]:
df_filtered = df[df["housing_median_age"] <= 100]
print("Original DataFrame shape:", df.shape)
print("Filtered DataFrame shape:", df_filtered.shape)
display(df_filtered.head())

Original DataFrame shape: (17000, 9)
Filtered DataFrame shape: (17000, 9)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [24]:
print(df["housing_median_age"].max())

52